server:
  domain: "registry.example.com"
  address: "0.0.0.0"
  port: "5050"
token:
  issuer: "distribution-token-server"
  expiration: 36000
secureModule: true
tls:
  cert: "/tmp/cert/server.pem"
  key: "/tmp/cert/server.key"
