server:
  domain: "registry.example.com"
  address: "0.0.0.0"
  port: "5050"
token:
  issuer: "distribution-token-server"
  expiration: 36000
secureModule: false
tls:
  cert: "/media/cert/server.crt"
  key: "/media/cert/server.key"
